version: '3.8'

services:
  redis:
    image: redis:6.2.6
    command: redis-server --port 6379
    container_name: redis_server
    hostname: redis_server
    ports:
        - 6379:6379

  my-chat:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    command: >
      python chat/main.py
